#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x2209D6902F969C95 (meissner@suse.de)
#
Name     : gphoto2
Version  : 2.5.26
Release  : 12
URL      : https://sourceforge.net/projects/gphoto/files/gphoto/2.5.26/gphoto2-2.5.26.tar.gz
Source0  : https://sourceforge.net/projects/gphoto/files/gphoto/2.5.26/gphoto2-2.5.26.tar.gz
Source1  : https://sourceforge.net/projects/gphoto/files/gphoto/2.5.26/gphoto2-2.5.26.tar.gz.asc
Summary  : Command line interface to libgphoto2
Group    : Development/Tools
License  : GPL-2.0
Requires: gphoto2-bin = %{version}-%{release}
Requires: gphoto2-license = %{version}-%{release}
Requires: gphoto2-locales = %{version}-%{release}
Requires: gphoto2-man = %{version}-%{release}
BuildRequires : libgphoto2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : popt-dev
BuildRequires : readline-dev

%description
gphoto2 is a command line client to for the libgphoto2. It allows to
use gPhoto software from a terminal or from a script shell to perform
any camera operation that can be done. This is the main user interface.

%package bin
Summary: bin components for the gphoto2 package.
Group: Binaries
Requires: gphoto2-license = %{version}-%{release}

%description bin
bin components for the gphoto2 package.


%package doc
Summary: doc components for the gphoto2 package.
Group: Documentation
Requires: gphoto2-man = %{version}-%{release}

%description doc
doc components for the gphoto2 package.


%package license
Summary: license components for the gphoto2 package.
Group: Default

%description license
license components for the gphoto2 package.


%package locales
Summary: locales components for the gphoto2 package.
Group: Default

%description locales
locales components for the gphoto2 package.


%package man
Summary: man components for the gphoto2 package.
Group: Default

%description man
man components for the gphoto2 package.


%prep
%setup -q -n gphoto2-2.5.26
cd %{_builddir}/gphoto2-2.5.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604620474
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1604620474
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gphoto2
cp %{_builddir}/gphoto2-2.5.26/COPYING %{buildroot}/usr/share/package-licenses/gphoto2/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
%make_install
%find_lang gphoto2

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gphoto2

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/gphoto2/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gphoto2/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gphoto2.1

%files locales -f gphoto2.lang
%defattr(-,root,root,-)

